version: '3.8'
services:
  nginx:
    image: nokmaster/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - nok-network

volumes:
  redis-data:

networks:
  nok-network:
    name: nok-network
