version: '3.8'
services:
  nginx:
    image: nokmaster/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nok-network


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-calendars-container
    restart: always
    volumes:
      - ./config/prometheus/prometheus-local.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - nok-network

networks:
  nok-network:
    name: nok-network
