version: "3"

services:
  backend:
    image: nokmaster/backend
    container_name: backend
    hostname: backend
    env_file:
      - .env
    expose:
      - "8080"

  nginx:
    image: nokmaster/nginx
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-calendars-container
    volumes:
      - ./config/prometheus/prometheus-local.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      calendars_network:
        ipv4_address: ${NETWORK_PROMETHEUS_IP}