version: '3.8'
services:
  nginx:
    image: nokmaster/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nok-network

networks:
  nok-network:
    name: nok-network
