version: '3.8'

services:
  green:
    image: nokmaster/backend
    container_name: green
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - PROFILES=green
      - ENV=green
    networks:
      - nok-network

networks:
  nok-network:
    external: true